spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springSecurity  # Replace with your MySQL URL
    username: root                # Replace with your MySQL username
    password: 9274@Indian                # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL driver class name

  jpa:
    hibernate:
      ddl-auto: create-drop                      # You can use other options like "update" or "validate"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql                              # Set the database type to MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
